# Indices de perception
NEIGHBORHOOD_UP = 0
NEIGHBORHOOD_DOWN = 1
NEIGHBORHOOD_RIGHT = 2
NEIGHBORHOOD_LEFT = 3
NEIGHBORHOOD_DIST_UP = 4
NEIGHBORHOOD_DIST_DOWN = 5
NEIGHBORHOOD_DIST_RIGHT = 6
NEIGHBORHOOD_DIST_LEFT = 7
PLAYER_X = 8
PLAYER_Y = 9
COMMAND_CENTER_X = 10
COMMAND_CENTER_Y = 11
AGENT_X = 12
AGENT_Y = 13
CAN_FIRE = 14
HEALTH = 15
